---
# tasks/main.yml
- name: Copy kubeadm config file
  copy:
    src: kubeadm-config.yaml
    dest: /root/kubeadm-config.yaml

- name: Initialize Kubernetes on controller node
  shell: kubeadm init --config=/root/kubeadm-config.yaml
  args:
    creates: /etc/kubernetes/admin.conf

- name: Ensure kubeconfig environment variable is set for the current user
  lineinfile:
    path: ~/.bashrc
    regexp: '^export KUBECONFIG='
    line: 'export KUBECONFIG=/etc/kubernetes/admin.conf'
    state: present

- name: Source ~/.bashrc to apply changes
  shell: source ~/.bashrc
  args:
    executable: /bin/bash
- name: Helm 저장소 추가
  command: helm repo add projectcalico https://docs.tigera.io/calico/charts
  changed_when: false

- name: Helm 저장소 업데이트
  command: helm repo update
  changed_when: false

- name: "Kubernetes 네임스페이스 {{ calico_namespace }} 생성"
  kubernetes.core.k8s:
    name: "{{ calico_namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: "Helm을 이용하여 Calico 설치 (버전 {{ calico_version }})"
  command: >
    helm install calico projectcalico/tigera-operator --version {{ calico_version }} --namespace {{ calico_namespace }}
  args:
    creates: "/etc/kubernetes/manifests/calico_installed"

- name: "Control Plane 노드 Taint 제거"
  command: kubectl taint node node1.example.com node-role.kubernetes.io/control-plane:NoSchedule-
  ignore_errors: true

- name: Calico CRD 적용
  kubernetes.core.k8s:
    state: present
    namespace: calico-system
    definition: "{{ lookup('template', 'calico-quay-crd.yaml.j2') }}"